on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # - name: Install Core dependencies
      #   run: npm install @actions/core
      # - name: Install Action dependencies
      #   run: npm install @actions/github 
        
      - name: Hello world action step
        id: hello
        uses: DeclanRodgers/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Jack Sparrow'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        